### ISSUE TITLE
Error On Startup

### ISSUE THREAD

**Issue by 839274509162738** [Stardust-kyun/dotfiles#10]
Details:
- OS: Arch Linux
- Running on virtualbox
- Awesome version = "v4.3 (Too long)" - latest

Hello, I've recently discovered your project and have attempted to use it. After setup and configuration and upon a reboot I began to receive the following error:
![image](https://github.com/Stardust-kyun/dotfiles/assets/135561487/83afc3fe-d0f8-4a7b-9390-a53e1353c018)

Also, as you can see in the image there is no visible DE customization that has taken place. Now presumably this is an error of mine and I have probably messed something up so I was wondering if i could get some guidance as to how to fix it.

Taking a look at the code (in line 50, as mentioned in the error):
![image](https://github.com/Stardust-kyun/dotfiles/assets/135561487/083978c6-f889-4c4c-9d40-1fde4976cd02)

To my knowledge, "naughty" is something in relation to awesomewm itself and there should be no errors as all the code is doing is handling error notifications (i guess). I did some slight research and seen on another github issue that the user had to build awesomewm from source, which may be my issue as I installed awesome-git from the aur via paru. I'm not exactly sure as to what to do to fix this so any help would be appreciated.

**Comment by javacafe01** [comment]
@839274509162738 You're using the wrong version of AwesomeWM.

Read the [README](https://github.com/Stardust-kyun/dotfiles#minimal-installation-packages)

**Comment by javacafe01** [comment]
Just realized that you installed awesome-git. Well, you are still using the wrong version, as `naughty` does not have `connect_signal` only in AwesomeWM stable

**Comment by 839274509162738** [comment]
> Just realized that you installed awesome-git. Well, you are still using the wrong version, as `naughty` does not have `connect_signal`, which is only in AwesomeWM stable according to the docs

Thanks lol. I assumed i was just being dumb

**Comment by 839274509162738** [comment]
Resolved
