### ISSUE TITLE
Error on reboot

### ISSUE THREAD

**Issue by salviija** [Stardust-kyun/dotfiles#7]
On reboot, awesome default configs appear with the error /home/usr/.config/awesome/config/bind.lua:2: attempt to index a nil value (global user)

if there is any more information I may give you to help solve this issue please ask! I don't think it's an issue with the dotfiles but rather my system

**Comment by Stardust-kyun** [comment]
Hi there! It seems like there's something wrong with the user table stored in ~/.config/awesome/json/user.json . Does the file exist for you?

**Comment by salviija** [comment]
it does exist now... the problem was on my part, sorry for clogging the repo

**Comment by Stardust-kyun** [comment]
No problem at all -- could you add what you did to fix it? Several other people have had this issue and it would be great to know the solution!

**Comment by Stardust-kyun** [comment]
No longer an issue as tables are stored locally and checked on startup.
