### ISSUE TITLE
Error in init.lua

### ISSUE THREAD

**Issue by Chenomorfo** [Stardust-kyun/dotfiles#8]
I think is an issue made by me, but I want to know why.

The error says: "/home/myProfile/.config/awesome/json/init.lua:1636: invalid conversion specification: '%0s'

I know really a little bit about lua, so is so hard to me catch the error.

Will you tell me where is the fix of this? or how can I test a lua file for check errors?

**Comment by Regis-Loyaute** [comment]
Maybe say first what you did if you say that this issue was caused by an action you took ?

**Comment by Stardust-kyun** [comment]
Fixed a while back by editing the json library.
