### ISSUE TITLE
obsidian readlink won't work

### ISSUE THREAD

**Issue by M3CHR0M4NC3R** [Stardust-kyun/dotfiles#9]
I just read your method for grabbing the exec path from client pids, but for obsidian, that will return the path to electron30. Perhaps there should be a catch for that specific window that calls `whereis obsidian`. Anki also exhibits this behavior, pointing to python instead.

**Comment by Stardust-kyun** [comment]
Yeah, getting the executable from PID doesn't work 100% of the time. Rather than hardcoding exceptions, I would recommend editing `~/.config/awesome/json/dock.json` to use the correct executable. Adding fallback methods is on the todo list.

**Comment by M3CHR0M4NC3R** [comment]
sounds good enough to me
